### ISSUE TITLE
Midi Note data

### ISSUE THREAD

**Issue by wchorski** [shaltiel/42Noir-UnityEasyController#2]
I see it takes cc data just fine, but what about note data? anyway to get keys or pads linked up?

**Comment by shaltiel** [comment]
Hi, that will be added very soon, few users need this feature, please send me over an email and I will send you the free update once it’s ready.

**Comment by antiero** [comment]
Also interested in MIDI note data here! Have there been any updates for this?

**Comment by shaltiel** [comment]
Hi now it’s available in the new version. If you have the previous version, send us an email and will send you v2!
